apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`{{ .Values.network.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: 80
  tls:
    secretName: {{ .Values.network.host }}
