{{- if or .Values.openhab.setup.passwordHash.value .Values.openhab.setup.passwordSalt.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-internal
type: Opaque
stringData:
  {{- if .Values.openhab.setup.passwordHash.value }}
  passwordHash: {{ .Values.openhab.setup.passwordHash.value | quote }}
  {{- end }}
  {{- if .Values.openhab.setup.passwordSalt.value }}
  passwordSalt: {{ .Values.openhab.setup.passwordSalt.value | quote }}
  {{- end }}
{{- end }}
