apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jsondb
type: Opaque
stringData:
  users.json: |
    {
      "{{ .Values.openhab.setup.adminUser }}": {
        "class": "org.openhab.core.auth.ManagedUser",
        "value": {
          "name": "{{ .Values.openhab.setup.adminUser }}",
          "passwordHash": "{{ .Values.openhab.setup.passwordHash }}",
          "passwordSalt": "{{ .Values.openhab.setup.passwordSalt }}",
          "roles": ["administrator"],
          "sessions": [],
          "apiTokens": []
        }
      }
    }
  uicomponents_ui_page.json: |
    {
      {{- $first := true -}}
      {{- range $id, $page := .Values.openhab.setup.uiPages }}
      {{- if not $first }},{{ end }}
      "{{ $id }}": {
        "class": "org.openhab.core.ui.components.RootUIComponent",
        "value": {
          "uid": "{{ $id }}",
          "component": "{{ $page.component }}",
          "config": { "label": "{{ $page.label }}" },
          "slots": { "default": [] }
        }
      }
      {{- $first = false -}}
      {{- end }}
    }
